# Generated by Django 5.1.5 on 2025-02-07 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='preferences',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='recommendations',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='weather_conditions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='budget',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
